"use client";
import { useEffect, useState } from 'react';
import axios from 'axios';
import { motion } from 'framer-motion';
import { KeyRound, Plus, Lock, Unlock, Trash2, Users } from 'lucide-react';
import toast from 'react-hot-toast';

type ConnectionKey = {
  id: string;
  keyString: string;
  status: string;
  createdAt: string;
  expiresAt: string | null;
  note: string | null;
};

export default function AdminPage() {
  const [keys, setKeys] = useState<ConnectionKey[]>([]);
  const [newKey, setNewKey] = useState('');
  const [loading, setLoading] = useState(false);

  const fetchKeys = async () => {
    try {
      const res = await axios.get('https://dasd-1z1t.onrender.com/api/admin/keys');
      setKeys(res.data);
    } catch (error) {
      toast.error("Không thể tải danh sách Keys");
    }
  };

  useEffect(() => {
    fetchKeys();
  }, []);

  const generateKey = () => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    const segment = () => Array.from({length: 4}, () => chars[Math.floor(Math.random() * chars.length)]).join('');
    return `minitech-${segment()}-${segment()}`;
  };

  const handleCreateKey = async () => {
    try {
      setLoading(true);
      const generatedKey = generateKey();
      await axios.post('https://dasd-1z1t.onrender.com/api/admin/keys', {
        keyString: generatedKey,
        note: newKey || 'Generated by Admin'
      });
      toast.success("Tạo Key thành công!");
      setNewKey('');
      fetchKeys();
    } catch (error) {
      toast.error("Lỗi khi tạo Key");
    } finally {
      setLoading(false);
    }
  };

  const handleUpdateStatus = async (id: string, status: string) => {
    try {
      await axios.patch(`https://dasd-1z1t.onrender.com/api/admin/keys/${id}/status`, { status });
      toast.success("Cập nhật thành công!");
      fetchKeys();
    } catch (error) {
      toast.error("Cập nhật thất bại");
    }
  };

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-gray-200 p-8">
      <div className="max-w-6xl mx-auto space-y-8">
        
        {/* Header */}
        <header className="flex items-center justify-between pb-8 border-b border-gray-800">
          <div>
            <h1 className="text-3xl font-bold text-white flex items-center gap-3">
              <KeyRound className="text-blue-500" /> Quản lý Connection Keys
            </h1>
            <p className="text-gray-400 mt-2">Tạo và quản lý các khóa kết nối an toàn cho hệ thống nhắn tin.</p>
          </div>
          <div className="flex gap-4">
            <input 
              type="text" 
              placeholder="Ghi chú (Tùy chọn)" 
              value={newKey}
              onChange={(e) => setNewKey(e.target.value)}
              className="px-4 py-2 bg-[#1a1a1a] border border-gray-800 rounded-lg text-white"
            />
            <button
              onClick={handleCreateKey}
              disabled={loading}
              className="px-6 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg flex items-center gap-2 font-medium transition"
            >
              <Plus className="w-4 h-4" /> Tạo Key mới
            </button>
          </div>
        </header>

        {/* List */}
        <div className="grid gap-4">
          {keys.map((key) => (
            <motion.div 
              key={key.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-[#111111] border border-gray-800 rounded-xl p-6 flex items-center justify-between hover:border-gray-700 transition"
            >
              <div>
                <h3 className="text-2xl font-mono text-white tracking-widest">{key.keyString}</h3>
                <div className="flex items-center gap-4 mt-2 text-sm text-gray-400">
                  <span>Tạo lúc: {new Date(key.createdAt).toLocaleString()}</span>
                  {key.note && <span>• Ghi chú: {key.note}</span>}
                </div>
              </div>
              
              <div className="flex items-center gap-4">
                <span className={`px-3 py-1 text-xs font-medium rounded-full ${
                  key.status === 'ACTIVE' ? 'bg-green-500/10 text-green-500 border border-green-500/20' : 
                  'bg-red-500/10 text-red-500 border border-red-500/20'
                }`}>
                  {key.status}
                </span>

                <div className="flex items-center gap-2 border-l border-gray-800 pl-4">
                  {key.status === 'ACTIVE' ? (
                    <button 
                      onClick={() => handleUpdateStatus(key.id, 'LOCKED')}
                      className="p-2 text-gray-400 hover:text-red-500 hover:bg-red-500/10 rounded-lg transition"
                      title="Khóa Key"
                    >
                      <Lock className="w-5 h-5" />
                    </button>
                  ) : (
                    <button 
                      onClick={() => handleUpdateStatus(key.id, 'ACTIVE')}
                      className="p-2 text-gray-400 hover:text-green-500 hover:bg-green-500/10 rounded-lg transition"
                      title="Mở khóa Key"
                    >
                      <Unlock className="w-5 h-5" />
                    </button>
                  )}
                </div>
              </div>
            </motion.div>
          ))}
          
          {keys.length === 0 && (
            <div className="text-center py-20 text-gray-500">
              <KeyRound className="w-12 h-12 mx-auto mb-4 opacity-20" />
              <p>Chưa có Connection Key nào.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
